[package]
name = "centipede"
version = "0.2.9"
authors = [
    "Omer <omer@kzencorp.com>",
    "Gary <gary@kzencorp.com>"
]

[lib]
crate-type = ["lib"]

[dependencies]
curv = { git = "https://github.com/KZen-networks/curv", tag = "v0.5.9"}
bulletproof = {git = "https://github.com/KZen-networks/bulletproofs", tag = "v1.1.3"}
serde_derive = "1.0"
serde = "1.0"
rayon = "1.0.3"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "v_backup"
path = "benches/v_backup.rs"
harness = false
